name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # Replace with the name of the branch that triggers the action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Copy build output
        run: cp -r dist/* .

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'Deploy build output to gh-pages branch'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true # This will overwrite the existing branch content, use with caution
